### ISSUE TITLE
coco_synset_categories range between 1 to 90, but there are 80 classes in coco

### ISSUE THREAD

**Issue by Melika-Ayoughi** [lvis-dataset/lvis-api#16]
## ❓ Questions and Help
Hi! I have a question regarding  "lvis-api/data/coco_to_synset.json" file: in the COCO_SYNSET_CATEGORIES where each synset is mapped to a coco id, the ids range from 1 to 90, which means 10 ids are not present since there are only 80 classes in coco. This causes classes that have a coco id>80 to not count in the evaluation (like it is in detectron2). Why did u choose to do this?

**Comment by rbgirshick** [comment]
The COCO dataset uses non-contiguous category ids that range from 1 to 90 (see annotation json files from https://cocodataset.org/#download). The provided mapping uses the COCO non-contiguous category ids since they are canonical and do not dependent on a particular object detection library (e.g., detectron2, mmdet, etc.).
