### ISSUE TITLE
LVIS doesn't detect people

### ISSUE THREAD

**Issue by antoniofurioso** [lvis-dataset/lvis-api#28]
## ❓ Questions and Help

Hello everyone, I'm trying to use detectron2 with LVIS and I see that I'm unable to detect people using LVIS instances.

Someone could tell me why?

Thank you for your help.

**Comment by rbgirshick** [comment]
The reason is given in Section 2.2 paragraph "Reduced Workload" of the LVIS paper. The most frequent categories in LVIS are heavily subsampled in order to allocate annotation budget for less frequent categories (cf. COCO in which 30% of all annotated instances are people). So the simple reason is that compared to COCO there are relatively few annotated people and our detectors do not perform well when annotations are limited, which is the core challenge posed by LVIS.

**Comment by antoniofurioso** [comment]
Thank you for explaining why.

So if I want to detect people along with the other objects, I need to add an additional annotation file, right?

**Comment by rbgirshick** [comment]
For this case, I would recommend training on the union of COCO and LVIS annotations.
