### ISSUE TITLE
LVIS to WordNet mapping

### ISSUE THREAD

**Issue by kumgleb** [lvis-dataset/lvis-api#35]
## ❓ Questions and Help
Hi!

**Short question:**
Is there are file like https://github.com/lvis-dataset/lvis-api/blob/master/data/coco_to_synset.json, but for all LVIS labels?

**In more details:**
According to the paper, as far as I understood, all LVIS labels should be a subset of WordNet synsets.

> The resulting vocabulary contains 1723 synsets—the upper bound on the number of categories that can appear in LVIS.

I explore intersection between LVIS labels and WordNet noun synsets, and there are 15 labels that has no exact match at a first glance. But all of them can be found in a WordNet using different names, for example:
* baseball_base -> home_plate.n.01
* boom_microphone -> boom.n.03
* brass_plaque -> brass.n.07
* etc.

Such a correspondences I perform manually wrt synset description and image examples, as a result I confident that labels has exactly the same meaning as a synsets.

For the rest of the labels it is overwhelming to find correspondence manually, but if I do it just by word matching it can lead to a mistakes, for example:

For a label **vent** from LVIS there are 5 different noun synsets from WordNet, such as:
* **vent.n.01** (hole for the escape of gas or air)
*  **vent.n.03** (a fissure in the earth's crust)
*  **vent.n.04** (a slit in a garment), 
* etc. <br>

And wrt LVIS images only first is the right one.

**So my question is**: how can I find such LVIS labels to WordNet synset correspondences automatically, whether it is possible?

**Comment by rbgirshick** [comment]
Hi @kumgleb, yes this information is available for all LVIS categories. You can find it in the `synset` field of the `categories` structure in the LVIS json files (as documented here https://www.lvisdataset.org/dataset). We say there that the categories are "loosely" based on WordNet because in many cases we manually edited the synset definition, which origially came from WordNet, to make it clearer to annotators. The meanings are still largely aligned with WordNet, but in some cases the definitions were too narrow, too verbose, or too convoluted for annotators to easily apply.
